/**
 * DraftSkill Schema - DAL Builder
 *
 * The canonical object shared by chat and UI. Replaces project.json + toolbox.json.
 * @module types/DraftSkill
 */

/**
 * @typedef {'PROBLEM_DISCOVERY' | 'SCENARIO_EXPLORATION' | 'INTENT_DEFINITION' | 'TOOLS_PROPOSAL' | 'TOOL_DEFINITION' | 'POLICY_DEFINITION' | 'MOCK_TESTING' | 'READY_TO_EXPORT' | 'EXPORTED'} Phase
 */

/**
 * @typedef {'string' | 'number' | 'boolean' | 'object' | 'array'} DataType
 */

// ═══════════════════════════════════════════════════════════════
// SUPPORTING TYPES
// ═══════════════════════════════════════════════════════════════

/**
 * @typedef {Object} Scenario
 * @property {string} id
 * @property {string} title
 * @property {string} description
 * @property {string[]} steps
 * @property {string} expected_outcome
 */

/**
 * @typedef {Object} IntentEntity
 * @property {string} name
 * @property {DataType} type
 * @property {boolean} required
 * @property {'message' | 'context'} extract_from
 */

/**
 * @typedef {Object} IntentRateLimit
 * @property {number} max_per_session
 * @property {number} cooldown_seconds
 * @property {string} message
 */

/**
 * @typedef {Object} IntentGuardrails
 * @property {string[]} pre_conditions
 * @property {IntentRateLimit} [rate_limit]
 */

/**
 * @typedef {Object} Intent
 * @property {string} id
 * @property {string} description
 * @property {string[]} examples
 * @property {string} [maps_to_workflow] - workflow.id reference
 * @property {boolean} maps_to_workflow_resolved
 * @property {IntentEntity[]} [entities]
 * @property {IntentGuardrails} [guardrails]
 */

/**
 * @typedef {Object} ToolInput
 * @property {string} name
 * @property {DataType} type
 * @property {boolean} required
 * @property {string} description
 * @property {*} [default]
 * @property {string[]} [enum]
 */

/**
 * @typedef {Object} ToolOutput
 * @property {DataType} type
 * @property {string} description
 * @property {Object} [schema]
 */

/**
 * @typedef {Object} MockExample
 * @property {string} id
 * @property {Object} input
 * @property {*} output
 * @property {string} [description]
 */

/**
 * @typedef {Object} MockTestResult
 * @property {string} id
 * @property {string} timestamp
 * @property {Object} input
 * @property {*} [expected_output]
 * @property {*} actual_output
 * @property {boolean} passed
 * @property {string} [notes]
 */

/**
 * @typedef {Object} PolicyCondition
 * @property {string} when - Expression: "amount > 500"
 * @property {'allow' | 'deny' | 'escalate' | 'require_approval'} action
 * @property {string} [message]
 */

/**
 * @typedef {Object} ToolPolicy
 * @property {'always' | 'conditional' | 'never'} allowed
 * @property {PolicyCondition[]} [conditions]
 * @property {'always' | 'conditional' | 'never'} [requires_approval]
 * @property {string} [rate_limit] - e.g., "100/minute"
 */

/**
 * @typedef {Object} ToolMock
 * @property {boolean} enabled
 * @property {'examples' | 'llm' | 'hybrid'} mode
 * @property {MockExample[]} examples
 * @property {string[]} [llm_rules]
 */

/**
 * Tool source - describes where this tool comes from
 * @typedef {Object} ToolSource
 * @property {'mcp_bridge' | 'builtin' | 'custom'} type - Source type
 * @property {string} [connection_id] - Connector ID for mcp_bridge tools
 * @property {string} [mcp_tool] - Original tool name on MCP server
 */

/**
 * @typedef {Object} Tool
 * @property {string} id
 * @property {'temporary' | 'permanent'} id_status
 * @property {string} name
 * @property {string} description
 * @property {ToolInput[]} inputs
 * @property {ToolOutput} output
 * @property {ToolPolicy} policy - Inline policy (tool-level)
 * @property {ToolMock} mock - Mock configuration
 * @property {'untested' | 'tested' | 'skipped'} mock_status
 * @property {MockTestResult[]} [mock_test_results]
 * @property {ToolSource} [source] - Tool source (MCP bridge, builtin, custom)
 */

/**
 * Meta Tool - A higher-level abstraction that composes multiple direct tools
 * Auto-generated by DAL, not manually created by users
 * @typedef {Object} MetaTool
 * @property {string} id
 * @property {string} name - Display name (e.g., "Verify Refund Eligibility")
 * @property {string} description - What this meta tool achieves
 * @property {string[]} composes - Array of tool names this meta tool combines
 * @property {string} logic - Description of how the tools are combined (e.g., "Check order exists AND within return window")
 * @property {'pending' | 'approved' | 'rejected'} status - User approval status
 * @property {string} suggested_by - Always 'dal' for auto-generated
 * @property {string} [suggested_reason] - Why DAL suggested this meta tool
 * @property {string} created_at
 */

/**
 * @typedef {Object} ApprovalRule
 * @property {string} id
 * @property {string} tool_id - May be unresolved
 * @property {boolean} tool_id_resolved
 * @property {PolicyCondition[]} conditions
 * @property {string} [approver] - Role or queue
 */

/**
 * @typedef {Object} Workflow
 * @property {string} id
 * @property {string} name
 * @property {string} description
 * @property {string} trigger
 * @property {string[]} steps - Tool IDs (may be unresolved)
 * @property {boolean[]} steps_resolved - Per-step resolution status
 * @property {boolean} required - Must follow this sequence?
 * @property {'warn' | 'block' | 'ask_user'} [on_deviation]
 */

/**
 * @typedef {Object} ToolBoxImport
 * @property {string} import - ToolBox ID from registry
 * @property {string} version - Semver constraint
 * @property {Object} [overrides]
 * @property {Object} [overrides.tools]
 * @property {string[]} [overrides.tools.include]
 * @property {string[]} [overrides.tools.exclude]
 * @property {Object} [overrides.policy]
 */

/**
 * @typedef {Object} Channel
 * @property {'api' | 'slack' | 'email' | 'webhook'} type
 * @property {boolean} enabled
 * @property {Object} config
 */

/**
 * Per-skill connector configuration overrides
 * Allows skills to specify their own identity when using shared connectors
 * @typedef {Object} ConnectorConfig
 * @property {string} connector_id - Reference to connector ID (e.g., "gmail", "slack")
 * @property {Object} [identity] - Identity overrides for this connector
 * @property {string} [identity.from_name] - Display name for outgoing messages
 * @property {string} [identity.from_email] - Email address for outgoing emails
 * @property {string} [identity.signature] - Signature to append to messages
 * @property {Object} [defaults] - Default values for tool calls on this connector
 */

// ═══════════════════════════════════════════════════════════════
// TENANT & CHANNEL CONFIGURATION (Multi-Tenant Architecture)
// ═══════════════════════════════════════════════════════════════

/**
 * Actor types in the system
 * @typedef {'external_user' | 'skill_builder' | 'adas_builder' | 'agent' | 'service'} ActorType
 */

/**
 * Actor identity on a specific channel/provider
 * @typedef {Object} ActorIdentity
 * @property {'gmail' | 'slack' | 'whatsapp'} provider - Channel provider
 * @property {string} externalId - Identity on that provider (email, Slack user ID, etc.)
 */

/**
 * Actor - represents any entity (human or skill) that can send/receive messages
 * @typedef {Object} Actor
 * @property {string} actorId - UUID
 * @property {ActorType} actorType - Type of actor
 * @property {string} displayName - Display name
 * @property {ActorIdentity[]} identities - Channel identities
 * @property {string[]} roles - Assigned roles
 * @property {'active' | 'pending' | 'inactive'} status
 * @property {string} createdAt
 * @property {string} updatedAt
 */

/**
 * Email routing rule - maps email address to skill
 * @typedef {Object} EmailRoutingRule
 * @property {string} address - Email address (e.g., "swdev2@yourdomain.com")
 * @property {string} skill_slug - Target skill slug
 */

/**
 * Slack routing rule - maps mention/channel to skill
 * @typedef {Object} SlackRoutingRule
 * @property {string} [mention_handle] - Mention handle (e.g., "@swdev2") for mention-based routing
 * @property {string} [bot_user_id] - Slack bot user ID
 * @property {string} [channel_id] - Channel ID for channel-per-skill routing
 * @property {string} skill_slug - Target skill slug
 */

/**
 * Email channel configuration (tenant-level)
 * @typedef {Object} EmailChannelConfig
 * @property {boolean} enabled
 * @property {string} connector_id - Reference to MCP connector
 * @property {Object} routing
 * @property {'dedicated_mailbox' | 'plus_addressing'} routing.mode
 * @property {EmailRoutingRule[]} routing.rules
 */

/**
 * Slack channel configuration (tenant-level)
 * @typedef {Object} SlackChannelConfig
 * @property {boolean} enabled
 * @property {string} connector_id - Reference to MCP connector
 * @property {string} workspace_id - Slack workspace ID
 * @property {Object} routing
 * @property {'mention_based' | 'channel_per_skill'} routing.mode
 * @property {SlackRoutingRule[]} routing.rules
 */

/**
 * Tenant policies for actor management
 * @typedef {Object} TenantPolicies
 * @property {boolean} allow_external_users - Auto-provision actors for unknown senders
 * @property {string} [default_skill_slug] - Fallback skill if routing fails
 */

/**
 * Tenant configuration - defines communication channels and policies
 * @typedef {Object} TenantConfig
 * @property {string} tenant_id - UUID
 * @property {string} name - Tenant name
 * @property {Object} channels - Communication channels
 * @property {EmailChannelConfig} [channels.email]
 * @property {SlackChannelConfig} [channels.slack]
 * @property {TenantPolicies} policies
 * @property {string} createdAt
 * @property {string} updatedAt
 */

// ═══════════════════════════════════════════════════════════════
// SKILL IDENTITY & CHANNELS (Skill-Level Configuration)
// ═══════════════════════════════════════════════════════════════

/**
 * Skill's email identity
 * @typedef {Object} SkillEmailIdentity
 * @property {string} from_name - Display name in emails
 * @property {string} from_email - Email address (e.g., "swdev2@yourdomain.com")
 * @property {string} [signature] - Email signature
 */

/**
 * Skill's Slack identity
 * @typedef {Object} SkillSlackIdentity
 * @property {string} [bot_name] - Override bot display name
 * @property {string} [bot_icon_url] - Override bot icon
 */

/**
 * Skill identity - who the skill is (independent of channels)
 * @typedef {Object} SkillIdentity
 * @property {string} actor_ref - Logical reference to CORE actor (e.g., "agent::swdev2")
 * @property {string} display_name - Display name (e.g., "SWDev2 Bot")
 * @property {string} [avatar_url] - Avatar URL
 * @property {Object} [channel_identities] - Per-channel identity overrides
 * @property {SkillEmailIdentity} [channel_identities.email]
 * @property {SkillSlackIdentity} [channel_identities.slack]
 */

/**
 * Skill's inbound email configuration
 * @typedef {Object} SkillEmailInbound
 * @property {string[]} addresses - Email addresses that route to this skill
 */

/**
 * Skill's outbound email configuration
 * @typedef {Object} SkillEmailOutbound
 * @property {string} from_email - Email address to send from
 */

/**
 * Skill's inbound Slack configuration
 * @typedef {Object} SkillSlackInbound
 * @property {string[]} [mentions] - Mention handles (e.g., ["@swdev2"])
 * @property {string[]} [channels] - Channel IDs for channel-per-skill mode
 */

/**
 * Skill's outbound Slack configuration
 * @typedef {Object} SkillSlackOutbound
 * @property {string} bot_ref - Bot reference to use for sending
 */

/**
 * Skill channels configuration - how the skill is reached and responds
 * @typedef {Object} SkillChannelsConfig
 * @property {Object} [email]
 * @property {SkillEmailInbound} [email.inbound]
 * @property {SkillEmailOutbound} [email.outbound]
 * @property {Object} [slack]
 * @property {SkillSlackInbound} [slack.inbound]
 * @property {SkillSlackOutbound} [slack.outbound]
 */

// ═══════════════════════════════════════════════════════════════
// MESSAGE ATTRIBUTION & ROUTING
// ═══════════════════════════════════════════════════════════════

/**
 * Inbound event - normalized event from any channel
 * @typedef {Object} InboundEvent
 * @property {'gmail' | 'slack'} provider - Channel provider
 * @property {ActorIdentity} senderIdentity - Sender's channel identity
 * @property {string} senderActorId - Resolved sender actor UUID
 * @property {string} targetSkillSlug - Resolved target skill
 * @property {string} conversationKey - Stable thread/conversation key
 * @property {string} messageText - Message content
 * @property {string} [onBehalfOfActorId] - Delegation: original human actor
 * @property {string[]} [delegationChain] - Full delegation chain
 */

/**
 * Message attribution - who sent, who received, delegation
 * @typedef {Object} MessageAttribution
 * @property {string} senderActorId - Who actually sent (human or agent)
 * @property {string} targetSkillSlug - Which skill handles this
 * @property {string} [onBehalfOfActorId] - Human in delegation scenarios
 * @property {string[]} [delegationChain] - Full chain for nested delegation
 */

/**
 * Reply context - how to reply to a message
 * @typedef {Object} ReplyContext
 * @property {'email' | 'slack'} type - Channel type
 * @property {string} [to] - Email recipient
 * @property {string} [threadId] - Email thread ID
 * @property {string} [channelId] - Slack channel ID
 * @property {string} [threadTs] - Slack thread timestamp
 */

/**
 * Job metadata with attribution
 * @typedef {Object} JobMetadata
 * @property {string} jobId - UUID
 * @property {string} ownerActorId - Job owner (sender actor)
 * @property {string} skillActorId - Skill actor handling the job
 * @property {string} [onBehalfOfActorId] - Delegation: original human
 * @property {string[]} [delegationChain] - Full delegation chain
 * @property {'email' | 'slack' | 'api'} channel - Inbound channel
 * @property {ReplyContext} replyContext - How to reply
 */

// ═══════════════════════════════════════════════════════════════
// TRIGGER TYPES (Scheduler & Automation)
// ═══════════════════════════════════════════════════════════════

/**
 * Trigger type enumeration
 * @typedef {'schedule' | 'event'} TriggerType
 */

/**
 * Base trigger properties shared by all trigger types
 * @typedef {Object} BaseTrigger
 * @property {string} id - Unique identifier within the skill
 * @property {TriggerType} type - Type of trigger
 * @property {boolean} enabled - Whether trigger is active (default: true)
 * @property {number} concurrency - Max parallel jobs for this trigger (default: 1)
 * @property {string} prompt - Goal prompt passed to the triggered job
 * @property {Object} [input] - Arbitrary structured data passed to triggerContext.input
 */

/**
 * Schedule trigger - runs periodically based on ISO8601 duration
 * @typedef {Object} ScheduleTrigger
 * @property {string} id - Unique identifier within the skill
 * @property {'schedule'} type - Always 'schedule'
 * @property {boolean} enabled - Whether trigger is active (default: true)
 * @property {number} concurrency - Max parallel jobs (default: 1)
 * @property {string} prompt - Goal prompt for the triggered job
 * @property {Object} [input] - Arbitrary input passed to triggerContext
 * @property {string} every - ISO8601 duration (e.g., "PT2M" = 2 minutes, "PT1H" = 1 hour, "P1D" = 1 day)
 */

/**
 * Event trigger - runs when a matching event is received
 * @typedef {Object} EventTrigger
 * @property {string} id - Unique identifier within the skill
 * @property {'event'} type - Always 'event'
 * @property {boolean} enabled - Whether trigger is active (default: true)
 * @property {number} concurrency - Max parallel jobs (default: 1)
 * @property {string} prompt - Goal prompt for the triggered job
 * @property {Object} [input] - Arbitrary input passed to triggerContext
 * @property {string} event - Event type name (e.g., "email.received", "slack.message")
 * @property {Object} [filter] - Equality filter on event.data fields
 */

/**
 * Union type for all trigger types
 * @typedef {ScheduleTrigger | EventTrigger} Trigger
 */

/**
 * @typedef {Object} Message
 * @property {string} id
 * @property {'user' | 'assistant' | 'system'} role
 * @property {string} content
 * @property {string} timestamp
 * @property {Object} [state_update]
 * @property {SuggestedFocus} [suggested_focus]
 */

/**
 * @typedef {Object} SuggestedFocus
 * @property {'problem' | 'scenarios' | 'intents' | 'tools' | 'policy' | 'engine' | 'export'} panel
 * @property {string} [section]
 * @property {string} [field]
 * @property {'add' | 'edit' | 'review'} [action]
 */

/**
 * @typedef {Object} ValidationIssue
 * @property {string} code - e.g., "TOOL_NOT_FOUND"
 * @property {'error' | 'warning'} severity
 * @property {string} path - e.g., "policy.workflows[0].steps[2]"
 * @property {string} message
 * @property {string} [suggestion]
 */

/**
 * @typedef {Object} ValidationCompleteness
 * @property {boolean} problem
 * @property {boolean} scenarios
 * @property {boolean} role
 * @property {boolean} intents
 * @property {boolean} tools
 * @property {boolean} policy
 * @property {boolean} engine
 * @property {boolean} mocks_tested
 */

/**
 * @typedef {Object} ValidationUnresolved
 * @property {string[]} tools - Referenced but not defined
 * @property {string[]} workflows - Referenced but not defined
 * @property {string[]} intents - Referenced but not defined
 */

/**
 * @typedef {Object} ValidationResult
 * @property {boolean} valid - No blocking errors?
 * @property {boolean} ready_to_export - All requirements met?
 * @property {ValidationIssue[]} errors - Block progress
 * @property {ValidationIssue[]} warnings - Inform but allow
 * @property {ValidationUnresolved} unresolved
 * @property {ValidationCompleteness} completeness
 */

// ═══════════════════════════════════════════════════════════════
// MAIN DraftSkill INTERFACE
// ═══════════════════════════════════════════════════════════════

/**
 * @typedef {Object} Problem
 * @property {string} statement
 * @property {string} context
 * @property {string[]} goals
 */

/**
 * @typedef {Object} CommunicationStyle
 * @property {'formal' | 'casual' | 'technical'} tone
 * @property {'concise' | 'balanced' | 'detailed'} verbosity
 */

/**
 * @typedef {Object} Role
 * @property {string} name
 * @property {string} persona
 * @property {string[]} goals
 * @property {string[]} limitations
 * @property {CommunicationStyle} [communication_style]
 */

/**
 * @typedef {Object} IntentThresholds
 * @property {number} accept - Default: 0.8
 * @property {number} clarify - Default: 0.5
 * @property {number} reject - Default: 0.5
 */

/**
 * @typedef {Object} OutOfDomainConfig
 * @property {'redirect' | 'reject' | 'escalate'} action
 * @property {string} message
 * @property {string[]} [suggest_domains]
 */

/**
 * @typedef {Object} IntentsConfig
 * @property {Intent[]} supported
 * @property {IntentThresholds} thresholds
 * @property {OutOfDomainConfig} out_of_domain
 */

/**
 * @typedef {Object} FinalizationGate
 * @property {boolean} enabled - Whether to validate responses before sending (default: true)
 * @property {number} max_retries - How many times to retry if validation fails (default: 2)
 */

/**
 * @typedef {Object} RV2Config
 * @property {number} max_iterations - Default: 10
 * @property {number} iteration_timeout_ms - Default: 30000
 * @property {boolean} allow_parallel_tools - Default: false
 * @property {'escalate' | 'fail' | 'ask_user'} on_max_iterations
 */

/**
 * @typedef {Object} CriticConfig
 * @property {boolean} enabled
 * @property {number} check_interval - Default: 3
 * @property {'low' | 'medium' | 'high'} strictness
 */

/**
 * @typedef {Object} ReflectionConfig
 * @property {boolean} enabled
 * @property {'shallow' | 'medium' | 'deep'} depth
 */

/**
 * @typedef {Object} ReplanningConfig
 * @property {boolean} enabled
 * @property {number} max_replans - Default: 2
 */

/**
 * @typedef {Object} HLRConfig
 * @property {boolean} enabled - Default: true
 * @property {CriticConfig} critic
 * @property {ReflectionConfig} reflection
 * @property {ReplanningConfig} replanning
 */

/**
 * @typedef {Object} AutonomyConfig
 * @property {'autonomous' | 'supervised' | 'restricted'} level
 */

/**
 * @typedef {Object} ToolNotFoundConfig
 * @property {number} enter_resolution_after - Failures before entering RESOLUTION mode (default: 1)
 * @property {boolean} retryable - Whether this error type allows retry
 */

/**
 * @typedef {Object} ResolutionConfig
 * @property {number} max_iterations - Max iterations allowed in RESOLUTION mode (default: 1)
 * @property {string[]} allowed_capabilities - Capabilities allowed in RESOLUTION mode
 */

/**
 * @typedef {Object} LoopDetectionConfig
 * @property {boolean} enabled - Whether loop detection is active
 * @property {number} identical_call_threshold - Identical tool calls before flagging loop (default: 2)
 */

/**
 * @typedef {Object} InternalErrorConfig
 * @property {boolean} enabled - Whether internal error handling is active (default: true)
 * @property {ToolNotFoundConfig} tool_not_found - Tool-not-found error settings
 * @property {ResolutionConfig} resolution - RESOLUTION mode settings
 * @property {LoopDetectionConfig} loop_detection - Loop detection settings
 */

/**
 * @typedef {Object} EngineConfig
 * @property {string} [model] - LLM model to use (e.g., "claude-3-sonnet")
 * @property {number} [temperature] - LLM temperature (0.0-1.0)
 * @property {RV2Config} rv2
 * @property {HLRConfig} hlr
 * @property {AutonomyConfig} autonomy
 * @property {FinalizationGate} [finalization_gate] - Response validation before sending to user
 * @property {InternalErrorConfig} [internal_error] - Internal error handling and RESOLUTION mode
 */

/**
 * @typedef {Object} Guardrails
 * @property {string[]} never - Things agent must NEVER do
 * @property {string[]} always - Things agent must ALWAYS do
 */

/**
 * @typedef {Object} EscalationConfig
 * @property {boolean} enabled
 * @property {string[]} conditions
 * @property {string} target - queue name or handler
 */

/**
 * @typedef {Object} PolicyConfig
 * @property {Guardrails} guardrails
 * @property {ApprovalRule[]} approvals
 * @property {Workflow[]} workflows
 * @property {EscalationConfig} escalation
 */

/**
 * The main DraftSkill interface - canonical object for DAL Builder
 * @typedef {Object} DraftSkill
 * @property {string} id
 * @property {string} name
 * @property {string} description
 * @property {string} version
 * @property {Phase} phase
 * @property {string} [mcp_server] - MCP server URI for skill-specific tools (Multi-Slag Architecture)
 * @property {string} created_at
 * @property {string} updated_at
 * @property {Problem} problem
 * @property {Scenario[]} scenarios
 * @property {Role} role
 * @property {Object<string, string>} glossary
 * @property {IntentsConfig} intents
 * @property {EngineConfig} engine
 * @property {ToolBoxImport[]} toolbox_imports
 * @property {Tool[]} tools
 * @property {MetaTool[]} meta_tools - DAL-generated tool compositions
 * @property {string[]} [bootstrap_tools] - Up to 3 tool names always available to planner (pinned, not auto-executed)
 * @property {Trigger[]} triggers - Automation triggers (schedule, event)
 * @property {PolicyConfig} policy
 * @property {Channel[]} channels
 * @property {ConnectorConfig[]} [connector_configs] - Per-skill connector identity/config overrides (DEPRECATED: use skill_identity + skill_channels)
 * @property {SkillIdentity} [skill_identity] - Skill's identity (who the skill is)
 * @property {SkillChannelsConfig} [skill_channels] - Skill's channel configuration (how it's reached)
 * @property {ValidationResult} validation
 * @property {Message[]} conversation
 */

// ═══════════════════════════════════════════════════════════════
// PHASE DEFINITIONS
// ═══════════════════════════════════════════════════════════════

/**
 * All valid phases in order
 * @type {Phase[]}
 */
export const PHASES = [
  'PROBLEM_DISCOVERY',
  'SCENARIO_EXPLORATION',
  'INTENT_DEFINITION',
  'TOOLS_PROPOSAL',
  'TOOL_DEFINITION',
  'POLICY_DEFINITION',
  'MOCK_TESTING',
  'READY_TO_EXPORT',
  'EXPORTED'
];

/**
 * Phase display names
 * @type {Object<Phase, string>}
 */
export const PHASE_LABELS = {
  PROBLEM_DISCOVERY: 'Problem Discovery',
  SCENARIO_EXPLORATION: 'Scenario Exploration',
  INTENT_DEFINITION: 'Intent Definition',
  TOOLS_PROPOSAL: 'Tools Proposal',
  TOOL_DEFINITION: 'Tool Definition',
  POLICY_DEFINITION: 'Policy Definition',
  MOCK_TESTING: 'Mock Testing',
  READY_TO_EXPORT: 'Ready to Export',
  EXPORTED: 'Exported'
};

/**
 * Get phase index (for ordering)
 * @param {Phase} phase
 * @returns {number}
 */
export function getPhaseIndex(phase) {
  return PHASES.indexOf(phase);
}

/**
 * Check if phase1 comes before phase2
 * @param {Phase} phase1
 * @param {Phase} phase2
 * @returns {boolean}
 */
export function isPhaseBefore(phase1, phase2) {
  return getPhaseIndex(phase1) < getPhaseIndex(phase2);
}
