/**
 * Transforms an export bundle + connector sources into a flat file list
 * suitable for committing to a GitHub repo.
 *
 * Input: export bundle (from GET /deploy/solutions/:id/export) + connector sources
 * Output: [{ path, content }] — ready for githubService.pushFiles()
 */

import { isPlatformConnector } from './platformConnectorRegistry.js';

/**
 * Build the complete file list for a solution repo.
 *
 * @param {Object} exportBundle — from the /export endpoint
 * @param {Object} connectorSources — { connectorId: [{ path, content }] }
 * @returns {{ path: string, content: string }[]}
 */
export function buildRepoFiles(exportBundle, connectorSources = {}) {
  const files = [];
  const skipped = [];

  const solution = exportBundle.solution || {};
  const skills = exportBundle.skills || [];
  const connectors = exportBundle.connectors || [];

  // ── solution.json ──
  files.push({
    path: 'solution.json',
    content: JSON.stringify(solution, null, 2),
  });

  // ── skills/<skill-id>/skill.json ──
  for (const skill of skills) {
    const skillId = skill.id || skill.slug || 'unknown';
    files.push({
      path: `skills/${skillId}/skill.json`,
      content: JSON.stringify(skill, null, 2),
    });
  }

  // ── connectors/<connector-id>/* ──
  // Brief #2 phase A: SKIP platform-managed connectors entirely. Their source
  // lives in ai-dev-assistant/ and shouldn't be duplicated in user repos.
  // Pre-existing sentinel files in older repos still work (we just don't add
  // new ones); the cleanup script in phase C will remove them retroactively.
  for (const [connId, sourceFiles] of Object.entries(connectorSources)) {
    if (!Array.isArray(sourceFiles)) continue;
    if (isPlatformConnector(connId)) {
      skipped.push(connId);
      continue;
    }
    for (const file of sourceFiles) {
      // Skip binary placeholders
      if (file.content && file.content.startsWith('[binary file')) continue;
      if (file.content && file.content.startsWith('[file too large')) continue;
      files.push({
        path: `connectors/${connId}/${file.path}`,
        content: file.content || '',
      });
    }
  }

  if (skipped.length > 0) {
    console.log(`[githubRepoBuilder] Skipped ${skipped.length} platform connector(s) from repo push: ${skipped.join(', ')}`);
  }

  // ── .ateam/export.json — full re-importable bundle ──
  files.push({
    path: '.ateam/export.json',
    content: JSON.stringify(exportBundle, null, 2),
  });

  // ── .ateam/deployed_at.txt ──
  files.push({
    path: '.ateam/deployed_at.txt',
    content: new Date().toISOString(),
  });

  // ── README.md ──
  files.push({
    path: 'README.md',
    content: generateReadme(solution, skills, connectors),
  });

  return files;
}

/**
 * Generate a README from solution metadata.
 */
function generateReadme(solution, skills, connectors) {
  const lines = [];

  lines.push(`# ${solution.name || solution.id || 'A-Team Solution'}`);
  lines.push('');

  if (solution.description) {
    lines.push(solution.description);
    lines.push('');
  }

  lines.push('> Auto-generated by [A-Team](https://ateam-ai.com) — do not edit manually.');
  lines.push('> Use `ateam_github_push` to update from deployed state, or `ateam_github_patch` to edit files.');
  lines.push('');

  // Skills
  if (skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    for (const skill of skills) {
      const name = skill.identity?.name || skill.id || 'Unknown';
      const desc = skill.problem?.statement || skill.identity?.description || '';
      lines.push(`- **${name}** — ${desc}`);
    }
    lines.push('');
  }

  // Connectors
  if (connectors.length > 0) {
    lines.push('## Connectors');
    lines.push('');
    for (const conn of connectors) {
      const name = conn.name || conn.id || 'Unknown';
      const transport = conn.transport || 'stdio';
      lines.push(`- **${name}** (${transport})`);
    }
    lines.push('');
  }

  // Structure
  lines.push('## Repo Structure');
  lines.push('');
  lines.push('```');
  lines.push('solution.json          # Solution architecture');
  lines.push('skills/                # Skill definitions');
  lines.push('connectors/            # MCP connector source code');
  lines.push('.ateam/export.json     # Full re-importable bundle');
  lines.push('.ateam/deployed_at.txt # Last deploy timestamp');
  lines.push('```');
  lines.push('');

  lines.push('## Deploy from GitHub');
  lines.push('');
  lines.push('```');
  lines.push('ateam_github_pull(solution_id: "<solution-id>")');
  lines.push('```');

  return lines.join('\n');
}
