"""
MCP Server Template with Discovery Endpoints
Generated by ADAS MCP Toolbox Builder

This template provides:
- Full MCP server structure
- Skill/capability discovery endpoints
- Tool registration system
- Proper error handling and logging
"""

import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, asdict

from mcp.server.fastmcp import FastMCP

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# =============================================================================
# Domain Metadata (will be populated by generator)
# =============================================================================

SKILL_METADATA = {
    "id": "{{SKILL_ID}}",
    "name": "{{SKILL_NAME}}",
    "version": {{SKILL_VERSION}},
    "description": "{{SKILL_DESCRIPTION}}",
    "created_at": "{{CREATED_AT}}",
    "generator": "ADAS MCP Toolbox Builder",
    "role": {
        "name": "{{ROLE_NAME}}",
        "persona": "{{ROLE_PERSONA}}"
    }
}

DOMAIN_SCHEMA = {{DOMAIN_SCHEMA_JSON}}

TOOLS_REGISTRY: Dict[str, Dict[str, Any]] = {}


# =============================================================================
# Initialize MCP Server
# =============================================================================

mcp = FastMCP(SKILL_METADATA["name"])


# =============================================================================
# Discovery Endpoints
# =============================================================================

@mcp.tool()
def get_skill_info() -> dict:
    """
    Get metadata about this skill/domain.

    Returns:
        dict: Skill metadata including id, name, version, description, and role.
    """
    return {
        "status": "success",
        "skill": SKILL_METADATA,
        "tools_count": len(TOOLS_REGISTRY),
        "server_time": datetime.utcnow().isoformat()
    }


@mcp.tool()
def list_capabilities() -> dict:
    """
    List all available tools/capabilities in this MCP server.

    Returns:
        dict: List of all tools with their names, descriptions, and input schemas.
    """
    capabilities = []

    for tool_name, tool_info in TOOLS_REGISTRY.items():
        capabilities.append({
            "name": tool_name,
            "description": tool_info.get("description", ""),
            "category": tool_info.get("category", "general"),
            "inputs": tool_info.get("inputs", []),
            "output": tool_info.get("output", {}),
            "examples": tool_info.get("examples", [])
        })

    return {
        "status": "success",
        "skill_id": SKILL_METADATA["id"],
        "skill_name": SKILL_METADATA["name"],
        "capabilities": capabilities,
        "total_count": len(capabilities)
    }


@mcp.tool()
def get_tool_details(tool_name: str) -> dict:
    """
    Get detailed information about a specific tool.

    Args:
        tool_name: The name of the tool to get details for.

    Returns:
        dict: Detailed tool information including inputs, outputs, and examples.
    """
    if tool_name not in TOOLS_REGISTRY:
        return {
            "status": "error",
            "error": f"Tool '{tool_name}' not found",
            "available_tools": list(TOOLS_REGISTRY.keys())
        }

    tool_info = TOOLS_REGISTRY[tool_name]

    return {
        "status": "success",
        "tool": {
            "name": tool_name,
            **tool_info
        }
    }


@mcp.tool()
def get_domain_schema() -> dict:
    """
    Get the complete domain schema as JSON.

    Returns:
        dict: The full domain definition including all tools, policies, and configurations.
    """
    return {
        "status": "success",
        "schema_version": "1.0",
        "domain": DOMAIN_SCHEMA
    }


@mcp.tool()
def health_check() -> dict:
    """
    Check the health status of this MCP server.

    Returns:
        dict: Health status including uptime and resource information.
    """
    return {
        "status": "healthy",
        "skill_id": SKILL_METADATA["id"],
        "version": SKILL_METADATA["version"],
        "timestamp": datetime.utcnow().isoformat(),
        "tools_loaded": len(TOOLS_REGISTRY)
    }


# =============================================================================
# Tool Registration Helper
# =============================================================================

def register_tool(
    name: str,
    description: str,
    inputs: List[Dict],
    output: Dict,
    category: str = "general",
    examples: Optional[List[Dict]] = None
):
    """
    Register a tool in the tools registry for discovery.

    Args:
        name: Tool name
        description: Tool description
        inputs: List of input parameter definitions
        output: Output schema definition
        category: Tool category for organization
        examples: Optional list of example inputs/outputs
    """
    TOOLS_REGISTRY[name] = {
        "description": description,
        "inputs": inputs,
        "output": output,
        "category": category,
        "examples": examples or []
    }
    logger.info(f"Registered tool: {name}")


# =============================================================================
# Domain Tools (will be generated below)
# =============================================================================

{{TOOLS_IMPLEMENTATION}}


# =============================================================================
# Meta-Tools (compositions)
# =============================================================================

{{META_TOOLS_IMPLEMENTATION}}


# =============================================================================
# Server Startup
# =============================================================================

def main():
    """Start the MCP server."""
    logger.info(f"Starting MCP Server: {SKILL_METADATA['name']} v{SKILL_METADATA['version']}")
    logger.info(f"Registered {len(TOOLS_REGISTRY)} tools")
    mcp.run()


if __name__ == "__main__":
    main()
