/**
 * uiActionsAutoDefaults — synthesize sensible default `uiActions` blocks for
 * plugin manifests that don't have one. Implements §20 of UI_ACTIONS_DESIGN.md
 * (auto-generated defaults for the long tail of plugins).
 *
 * Design decisions locked down in the §20 review:
 *   - Override semantics: REPLACE. Explicit `uiActions` (including {}) wins.
 *     We only synthesize when the field is `undefined`. This makes auto-vs-
 *     hand-authored distinguishable and gives authors full control.
 *   - Generation timing: deploy-time. The synthesized block is written into
 *     the manifest as it flows through the deploy pipeline, so it lands in
 *     mongo + GitHub. Greppable, debuggable, copy-editable by the author.
 *
 * Skip rules (return plugin unchanged):
 *   - plugin.uiActions is already defined (REPLACE rule)
 *   - plugin.type === "service" (headless — no UI to render chips on)
 *   - plugin.internal === true (utility plugins not meant for the planner)
 *   - we cannot derive at least one intent (no commands AND no inferable
 *     entity kinds → empty `intents:{}` would be invalid per spec)
 *
 * Heuristics for synthesis:
 *   surfaces: ["chip"]                         — only v1 surface
 *   deeplink: "?focus=:focusId"                — common case
 *   intents.suggested_action.tool_names        — from plugin.commands[]
 *   intents.view_entity.entity_kinds           — inferred from plugin id
 *
 * The block is tagged with `_autoGenerated: true` so dashboards / metrics
 * can distinguish authored vs synthesized blocks.
 */

// Map plugin-id suffix → likely entity kinds. Extend as new patterns emerge.
// Empty array = explicit "this plugin has no entity-focused view" (skip
// view_entity for utilities like settings/connections panels).
const ENTITY_KIND_BY_SUFFIX = {
  // Memory / knowledge
  "memories-panel":     ["memory"],
  "memory-panel":       ["memory"],
  "notes-panel":        ["note"],
  "knowledge-panel":    ["document"],

  // Time-based
  "triggers-panel":     ["trigger", "reminder"],
  "trigger-panel":      ["trigger", "reminder"],
  "reminders-panel":    ["reminder"],
  "schedule-panel":     ["event", "appointment"],
  "calendar-panel":     ["event", "appointment"],
  "events-panel":       ["event"],
  "appointments-panel": ["appointment"],

  // Tasks / projects
  "tasks-panel":        ["task"],
  "todos-panel":        ["task"],
  "projects-panel":     ["project"],

  // People / messaging
  "contacts-panel":     ["contact"],
  "people-panel":       ["contact"],
  "messages-panel":     ["message"],
  "emails-panel":       ["email"],
  "threads-panel":      ["thread"],

  // Files
  "files-panel":        ["file"],
  "documents-panel":    ["document"],

  // Places / IoT
  "places-panel":       ["place"],
  "locations-panel":    ["place"],
  "devices-panel":      ["device"],
  "home-layout-panel":  ["device", "scene"],

  // Health / lifestyle
  "nutrition-dashboard":["meal", "food"],
  "workouts-panel":     ["workout"],
  "health-panel":       ["measurement"],

  // Explicit utilities — view_entity makes no sense
  "connections-panel":  [],
  "settings-panel":     [],
  "auth-webview":       [],
  "browser-view":       [],
  "pa-dashboard":       [],
  "whatsapp-setup":     [],
  "nutrition-camera":   [],
  "teach-panel":        [], // teaching flow, not entity browse
};

/**
 * Infer entity kinds for a plugin from its id. Returns [] if the suffix
 * is in the explicit-utility list, the inferred set, or a generic fallback.
 *
 * @param {string} pluginId  e.g. "mcp:foo-mcp:memories-panel" or "memories-panel"
 * @returns {string[]}
 */
export function inferEntityKindsFromId(pluginId) {
  if (!pluginId || typeof pluginId !== "string") return [];
  const parts = pluginId.split(":");
  const name = parts[parts.length - 1] || "";

  // Direct mapping wins.
  if (Object.prototype.hasOwnProperty.call(ENTITY_KIND_BY_SUFFIX, name)) {
    return ENTITY_KIND_BY_SUFFIX[name].slice();
  }

  // Generic fallback: strip common UI suffixes, crude singularize.
  // "books-panel" → "books" → "book"; "pets-view" → "pets" → "pet".
  const stripped = name.replace(/-panel$|-view$|-dashboard$|-screen$/i, "");
  if (!stripped || stripped === name) return [];

  const singular =
    stripped.endsWith("ies") ? stripped.slice(0, -3) + "y" :
    stripped.endsWith("ses") ? stripped.slice(0, -2) :
    stripped.endsWith("s")   ? stripped.slice(0, -1) :
    stripped;
  return singular ? [singular] : [];
}

/**
 * Extract suggested-action tool names from a plugin's `commands[]`.
 * Commands can be strings or objects with various shape variants
 * ({ tool_name }, { name }, { tool }) — accept all.
 */
function extractToolNames(plugin) {
  const cmds = Array.isArray(plugin?.commands) ? plugin.commands : [];
  const out = [];
  for (const c of cmds) {
    if (typeof c === "string") {
      out.push(c);
    } else if (c && typeof c === "object") {
      const name = c.tool_name || c.toolName || c.name || c.tool;
      if (typeof name === "string" && name.length > 0) out.push(name);
    }
  }
  // Dedup, preserve order
  return [...new Set(out)];
}

/**
 * Pure function. Returns a result describing what (if anything) was synthesized.
 * Never mutates the input.
 *
 * @param {Object} plugin
 * @returns {{ plugin: Object, synthesized: boolean, reason: string, intents?: string[] }}
 */
export function enrichWithDefaultUiActions(plugin) {
  if (!plugin || typeof plugin !== "object") {
    return { plugin, synthesized: false, reason: "not_object" };
  }
  if (plugin.uiActions !== undefined) {
    return { plugin, synthesized: false, reason: "explicit_uiActions" };
  }
  if (plugin.type === "service") {
    return { plugin, synthesized: false, reason: "service_type" };
  }
  if (plugin.internal === true) {
    return { plugin, synthesized: false, reason: "internal_flag" };
  }

  const intents = {};

  const toolNames = extractToolNames(plugin);
  if (toolNames.length > 0) {
    intents.suggested_action = { tool_names: toolNames };
  }

  const entityKinds = inferEntityKindsFromId(plugin.id || "");
  if (entityKinds.length > 0) {
    intents.view_entity = { entity_kinds: entityKinds };
  }

  if (Object.keys(intents).length === 0) {
    return { plugin, synthesized: false, reason: "no_intents_inferable" };
  }

  const enriched = {
    ...plugin,
    uiActions: {
      deeplink: "?focus=:focusId",
      surfaces: ["chip"],
      intents,
      _autoGenerated: true,
    },
  };

  return {
    plugin: enriched,
    synthesized: true,
    reason: "auto_default",
    intents: Object.keys(intents),
  };
}

/**
 * Apply enrichment to an array of plugins. Returns the new array + a summary
 * for logging / metrics. Used by the deploy pipeline to enrich solution.ui_plugins
 * and skill.ui_plugins before saving.
 *
 * @param {Array} plugins
 * @returns {{ plugins: Array, summary: { synthesized: Array, skipped: Array } }}
 */
export function enrichPluginList(plugins) {
  if (!Array.isArray(plugins)) return { plugins, summary: { synthesized: [], skipped: [] } };

  const out = [];
  const synthesized = [];
  const skipped = [];

  for (const p of plugins) {
    const r = enrichWithDefaultUiActions(p);
    out.push(r.plugin);
    if (r.synthesized) {
      synthesized.push({ id: p?.id, intents: r.intents });
    } else {
      skipped.push({ id: p?.id || "(unknown)", reason: r.reason });
    }
  }

  return { plugins: out, summary: { synthesized, skipped } };
}
